const STORAGE_KEY = 'airco_service_planner_v01';
const state = { customers: [], selectedId: null, agendaFilter: 'all' };
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const today = () => new Date(new Date().toDateString());
const addMonths = (date, months) => { const d = new Date(date); d.setMonth(d.getMonth() + Number(months || 12)); return d; };
const fmt = (d) => new Intl.DateTimeFormat('nl-NL', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(d));
const daysUntil = (date) => Math.ceil((new Date(date) - today()) / 86400000);
function load(){ const raw = localStorage.getItem(STORAGE_KEY); state.customers = raw ? JSON.parse(raw) : demoData(); save(); }
function save(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state.customers)); }
function statusFor(c){ const days = daysUntil(c.nextServiceDate); if(c.doneCount && days > 300) return {label:'gepland', cls:'done'}; if(days < 0) return {label:`${Math.abs(days)} dgn verlopen`, cls:'overdue'}; if(days <= 30) return {label:`over ${days} dgn`, cls:'soon'}; return {label:fmt(c.nextServiceDate), cls:''}; }
function showScreen(id){ $$('.screen').forEach(s=>s.classList.toggle('active', s.id===id)); $$('.bottom-nav button').forEach(b=>b.classList.toggle('active', b.dataset.screen===id)); $('#screenTitle').textContent = ({dashboardScreen:'Dashboard',customersScreen:'Klanten',newScreen:'Nieuwe installatie',agendaScreen:'Agenda',detailScreen:'Klantdetail'})[id] || 'Dashboard'; render(); }
function sortedCustomers(){ return [...state.customers].sort((a,b)=>new Date(a.nextServiceDate)-new Date(b.nextServiceDate)); }
function renderDashboard(){ const list = sortedCustomers(); const due = list.filter(c=>daysUntil(c.nextServiceDate)<=30); $('#activeCustomers').textContent = state.customers.length; $('#monthCount').textContent = list.filter(c=>new Date(c.nextServiceDate).getMonth()===today().getMonth()).length; $('#soonCount').textContent = due.length; $('#doneCount').textContent = state.customers.reduce((n,c)=>n+(c.doneCount||0),0); $('#todayCount').textContent = `${due.length} klanten`; $('#nextReminderText').textContent = due[0] ? `${due[0].name} staat als eerste klaar` : 'Geen onderhoud binnen 30 dagen'; $('#dueList').innerHTML = due.slice(0,4).map(cardHtml).join('') || `<div class="empty">Geen onderhoud nodig binnen 30 dagen.</div>`; }
function cardHtml(c){ const st=statusFor(c); return `<article class="customer-card" data-id="${c.id}"><div class="customer-top"><div><h4>${c.name}</h4><p>${c.address||'Geen adres'} · ${c.brand||'Airco'} ${c.model||''}</p><p>Volgend onderhoud: <strong>${fmt(c.nextServiceDate)}</strong></p></div><span class="badge ${st.cls}">${st.label}</span></div><div class="actions"><a href="tel:${c.phone}">Bel</a><a href="https://wa.me/${(c.phone||'').replace(/\D/g,'')}" target="_blank">WhatsApp</a><button class="primary-mini" data-action="detail" data-id="${c.id}">Open</button></div></article>`; }
function renderCustomers(){ const q = ($('#customerSearch')?.value||'').toLowerCase(); const list = sortedCustomers().filter(c => [c.name,c.address,c.brand,c.model].join(' ').toLowerCase().includes(q)); $('#customerList').innerHTML = list.map(cardHtml).join('') || `<div class="empty">Nog geen klanten gevonden.</div>`; }
function renderAgenda(){ let list = sortedCustomers(); if(state.agendaFilter==='overdue') list = list.filter(c=>daysUntil(c.nextServiceDate)<0); if(state.agendaFilter==='soon') list = list.filter(c=>daysUntil(c.nextServiceDate)<=30); $('#agendaList').innerHTML = list.map(cardHtml).join('') || `<div class="empty">Geen onderhoud in deze selectie.</div>`; }
function renderDetail(){ const c = state.customers.find(x=>x.id===state.selectedId); if(!c) return; const st=statusFor(c); $('#detailContent').innerHTML = `<div class="detail-card"><h2>${c.name}</h2><p>${c.address||'Geen adres ingevuld'}</p><span class="badge ${st.cls}">${st.label}</span><div class="info-grid"><div class="info"><span>Installatie</span><strong>${c.brand||'Airco'} ${c.model||''}</strong></div><div class="info"><span>Plaatsingsdatum</span><strong>${fmt(c.installDate)}</strong></div><div class="info"><span>Volgend onderhoud</span><strong>${fmt(c.nextServiceDate)}</strong></div><div class="info"><span>Interval</span><strong>Iedere ${c.intervalMonths} maanden</strong></div></div><div class="actions"><a href="tel:${c.phone}">📞 Bel klant</a><a href="https://wa.me/${(c.phone||'').replace(/\D/g,'')}" target="_blank">💬 WhatsApp</a><a href="mailto:${c.email}">✉️ Mail</a><button class="primary-mini" data-action="done" data-id="${c.id}">✓ Onderhoud uitgevoerd</button><button class="danger" data-action="delete" data-id="${c.id}">Verwijder</button></div></div>`; }
function render(){ renderDashboard(); renderCustomers(); renderAgenda(); if($('#detailScreen').classList.contains('active')) renderDetail(); }
function addCustomer(data){ const installDate = data.installDate; const next = addMonths(installDate, data.intervalMonths); state.customers.push({ id: crypto.randomUUID(), ...data, nextServiceDate: next.toISOString(), doneCount:0 }); save(); }
function markDone(id){ const c=state.customers.find(x=>x.id===id); if(!c) return; c.lastServiceDate = new Date().toISOString(); c.nextServiceDate = addMonths(new Date(), c.intervalMonths).toISOString(); c.doneCount = (c.doneCount||0)+1; save(); render(); }
function demoData(){ const base = today(); const d=(offset)=>{const x=new Date(base); x.setDate(x.getDate()+offset); return x.toISOString();}; return [{id:'1',name:'Jansen',address:'Rotterdam',phone:'0612345678',email:'jansen@mail.nl',brand:'Daikin',model:'Emura',installDate:d(-370),intervalMonths:'12',nextServiceDate:d(-5),doneCount:0},{id:'2',name:'De Vries',address:'Dordrecht',phone:'0687654321',email:'devries@mail.nl',brand:'Mitsubishi',model:'MSZ',installDate:d(-350),intervalMonths:'12',nextServiceDate:d(15),doneCount:0},{id:'3',name:'Bakker',address:'Barendrecht',phone:'0611122233',email:'bakker@mail.nl',brand:'LG',model:'DualCool',installDate:d(-200),intervalMonths:'12',nextServiceDate:d(165),doneCount:1}]; }
document.addEventListener('click', e=>{ const btn=e.target.closest('button,a'); if(!btn) return; if(btn.dataset.screen) showScreen(btn.dataset.screen); if(btn.dataset.action==='detail'){ state.selectedId=btn.dataset.id; showScreen('detailScreen'); } if(btn.dataset.action==='done') markDone(btn.dataset.id); if(btn.dataset.action==='delete'){ state.customers=state.customers.filter(c=>c.id!==btn.dataset.id); save(); showScreen('customersScreen'); } if(btn.dataset.action==='seed-demo'){ state.customers=demoData(); save(); render(); } if(btn.dataset.action==='export-csv'){ const csv=['Naam,Adres,Telefoon,Email,Merk,Model,Volgend onderhoud',...sortedCustomers().map(c=>[c.name,c.address,c.phone,c.email,c.brand,c.model,fmt(c.nextServiceDate)].join(','))].join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); a.download='onderhoud-agenda.csv'; a.click(); } if(btn.classList.contains('tab')){ state.agendaFilter=btn.dataset.filter; $$('.tab').forEach(t=>t.classList.toggle('active',t===btn)); renderAgenda(); } });
$('#installationForm').addEventListener('submit', e=>{ e.preventDefault(); const data = Object.fromEntries(new FormData(e.target).entries()); addCustomer(data); e.target.reset(); showScreen('customersScreen'); });
$('#customerSearch').addEventListener('input', renderCustomers);
load(); render();
