import assert from 'node:assert/strict';
import fs from 'node:fs';

const app=fs.readFileSync(new URL('../src/app.js',import.meta.url),'utf8');
const service=fs.readFileSync(new URL('../src/leads/lead-service.js',import.meta.url),'utf8');
const sql=fs.readFileSync(new URL('../supabase/leads_mailbox_v130.sql',import.meta.url),'utf8');
const sync=fs.readFileSync(new URL('../api/mailbox/sync.js',import.meta.url),'utf8');
const provider=fs.readFileSync(new URL('../api/_lib/mailbox-provider.js',import.meta.url),'utf8');
const crypto=fs.readFileSync(new URL('../api/_lib/mailbox-crypto.js',import.meta.url),'utf8');
const imap=fs.readFileSync(new URL('../api/_lib/imap-client.js',import.meta.url),'utf8');
const imapConnect=fs.readFileSync(new URL('../api/mailbox/imap-connect.js',import.meta.url),'utf8');
const auth=fs.readFileSync(new URL('../api/_lib/optera-auth.js',import.meta.url),'utf8');
const config=fs.readFileSync(new URL('../src/config.js',import.meta.url),'utf8');
const sw=fs.readFileSync(new URL('../public/service-worker.js',import.meta.url),'utf8');
const pkg=JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url),'utf8'));

assert.match(app,/nav\('leads'\)/,'Aanvragenroute ontbreekt');
assert.match(app,/Openstaande aanvragen \(\$\{leadItems\.length\}\)/,'Actielijst toont openstaande aanvragen');
assert.match(app,/leadInboxCache/,'Dashboardcache voor aanvragen ontbreekt');
assert.match(app,/Klant \+ opname inplannen/,'Directe vervolgactie ontbreekt');
assert.match(app,/await flushCloudSync\(\);[\s\S]*if\(schedule\)[\s\S]*await updateLead\(lead\.id,'reviewing',cid\)/,'Klant moet veilig in cloud staan en aanvraag moet open blijven totdat de opname echt is ingepland');
assert.match(app,/persistAppointmentForm\(savedAppointmentId, f\)[\s\S]*route\.leadId[\s\S]*await updateLead\(route\.leadId,route\.leadFinalStatus/,'Aanvraag mag pas na succesvol opslaan van de opname worden afgerond');
assert.match(app,/Microsoft 365 koppelen/);
assert.match(app,/Gmail \/ Google koppelen/);
assert.match(app,/Andere e-mailprovider \(IMAP\/SSL\)/,'Generieke IMAP-koppeling ontbreekt');
assert.match(app,/Klant klaarzetten/,'Aanvraag moet eerst beoordeeld worden voor klantconversie');
assert.match(app,/mailboxCallbackParam[\s\S]*route=\{name:'integrations'\}/,'OAuth-callback moet terugkeren naar Integraties');
assert.match(service,/list_leads_v130/);
assert.match(service,/\/api\/mailbox\/oauth-start/);
assert.match(service,/\/api\/mailbox\/imap-connect/,'Browser-service voor IMAP ontbreekt');
assert.match(service,/x-optero-organization-id/,'API-aanroepen moeten de actieve bedrijfsomgeving meesturen');
assert.match(sql,/create table if not exists public\.lead_intakes/);
assert.match(sql,/create table if not exists public\.mailbox_connections/);
assert.match(sql,/has_organization_role\(p_organization_id,array\['owner','planner'\]/,'Aanvragen zijn eigenaar-planner afgeschermd');
assert.match(sql,/public\.is_organization_owner\(p_organization_id\)/,'Integraties zijn eigenaar-only');
assert.match(sync,/existingCustomer/,'Bestaande klanten moeten uit nieuwe e-mailaanvragen worden gehouden');
assert.match(sync,/looksAutomated/,'Automatische e-mailfilter ontbreekt');
assert.match(provider,/Mail\.Read/,'Microsoft Mail.Read ontbreekt');
assert.match(provider,/gmail\.readonly/,'Gmail readonly scope ontbreekt');
assert.match(crypto,/aes-256-gcm/,'Refresh tokens moeten versleuteld worden opgeslagen');
assert.match(sql,/provider in \('microsoft','google','imap'\)/,'IMAP provider ontbreekt in database');
assert.match(imap,/tls\.connect/,'IMAP moet via TLS verbinden');
assert.match(imapConnect,/verifyImapConnection/,'IMAP-gegevens moeten vóór opslag worden gecontroleerd');
assert.match(imapConnect,/encryptSecret\(password\)/,'IMAP-wachtwoord moet versleuteld worden opgeslagen');
assert.match(auth,/x-optero-organization-id/,'Server moet de actieve organisatie valideren');
assert.ok(config.includes(`APP_VERSION = '${pkg.version} `));
assert.ok(sw.includes(`CACHE_NAME = 'optero-v${pkg.version}'`));
console.log('leads-inbox-v130: ok');
